import AutoGeneratedItem from '@ui/auto-generated-item';
import colors from '@utils/colors';
import {FC} from 'react';
import {FlatList, StyleSheet, Text, View} from 'react-native';
import {useFetchAutoGeneratedPlaylist} from 'src/hooks/query';

interface Props {}

const AutoGeneratedPlaylist: FC<Props> = props => {
  const {data, isLoading} = useFetchAutoGeneratedPlaylist();
  console.log(data);
  return (
    <View>
      <Text style={styles.label}>Playlist for You</Text>
      <FlatList
        horizontal
        showsHorizontalScrollIndicator={false}
        data={data}
        keyExtractor={item => item.id}
        renderItem={({item}) => <AutoGeneratedItem item={item} />}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  label: {
    color: colors.CONTRAST,
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 15,
  },
});

export default AutoGeneratedPlaylist;
