import {FC} from 'react';
import {FlatList, StyleSheet, Text, View} from 'react-native';
import {useDispatch} from 'react-redux';

import AutoGeneratedItem from '@ui/auto-generated-item';
import colors from '@utils/colors';
import {useFetchAutoGeneratedPlaylist} from 'src/hooks/query';
import LatestUploadsSkeleton from '@ui/skeletons/latest-uploads';
import {Playlist} from 'src/@types/playlist';

interface Props {
  onPlaylistPress(item: Playlist): void;
}

const AutoGeneratedPlaylist: FC<Props> = ({onPlaylistPress}) => {
  const {data, isLoading} = useFetchAutoGeneratedPlaylist();

  if (isLoading) return <LatestUploadsSkeleton />;
  return (
    <View>
      <Text style={styles.label}>Playlist for You</Text>
      <FlatList
        horizontal
        showsHorizontalScrollIndicator={false}
        data={data}
        keyExtractor={item => item.id}
        renderItem={({item}) => (
          <AutoGeneratedItem
            item={item}
            onPress={() => onPlaylistPress(item)}
          />
        )}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  label: {
    color: colors.CONTRAST,
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 15,
  },
});

export default AutoGeneratedPlaylist;
