import colors from '@utils/colors';
import {FC} from 'react';
import {Image} from 'react-native';
import {Pressable, StyleSheet, Text, View} from 'react-native';
import {Playlist} from 'src/@types/playlist';

interface Props {
  item: Playlist;
}

const AutoGeneratedItem: FC<Props> = ({item}) => {
  return (
    <Pressable style={styles.container}>
      <Image source={require('../../assets/music.png')} style={styles.image} />
      <View style={styles.overlay}>
        <Text style={styles.title}>{item.title}</Text>
        <Text style={styles.title}>{item.itemsCount}</Text>
      </View>
    </Pressable>
  );
};

const cardSize = 150;

const styles = StyleSheet.create({
  container: {
    width: cardSize,
    marginRight: 15,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.OVERLAY,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
  },
  image: {
    width: cardSize,
    height: cardSize,
    borderRadius: 5,
  },
  title: {
    color: colors.CONTRAST,
    fontWeight: 'bold',
    fontSize: 18,
  },
});

export default AutoGeneratedItem;
